// GENERATED by scripts/scaffold_aosp_modules.py — AOSP bp 1:1
// AOSP bp module: BiometricsSharedLib (bp path: shared/biometrics)
// Biometrics Shared Library (Udfps, PromptKind, etc.)

plugins {
    alias(libs.plugins.android.library)
    alias(libs.plugins.kotlin.android)
}

android {
    namespace = "com.android.systemui.shared.biometrics"
    compileSdkPreview = "SysUISdk"

    defaultConfig {
        minSdk = 32
    }

    sourceSets {
        getByName("main") {
            java.srcDirs("src/main/java")
            manifest.srcFile("src/main/AndroidManifest.xml")
        }
    }

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_21
        targetCompatibility = JavaVersion.VERSION_21
    }

    kotlin {
        jvmToolchain(21)
    }

    lint {
        abortOnError = false
    }

}

dependencies {
    compileOnly(files("${rootProject.projectDir}/libs/framework.jar"))
    implementation(libs.kotlin.stdlib)
}
