// GENERATED by scripts/scaffold_aosp_modules.py — AOSP bp 1:1
// AOSP bp module: api (bp path: pods/com/android/systemui/util/settings)
// Settings pod API (GlobalSettings, SecureSettings, etc.)

plugins {
    alias(libs.plugins.android.library)
    alias(libs.plugins.kotlin.android)
}

android {
    namespace = "com.android.systemui.util.settings"
    compileSdkPreview = "SysUISdk"

    defaultConfig {
        minSdk = 32
    }

    sourceSets {
        getByName("main") {
            java.srcDirs("src/main/java")
            manifest.srcFile("src/main/AndroidManifest.xml")
        }
    }

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_21
        targetCompatibility = JavaVersion.VERSION_21
    }

    kotlin {
        jvmToolchain(21)
    }

    lint {
        abortOnError = false
    }

}

dependencies {
    compileOnly(files("${rootProject.projectDir}/libs/framework.jar"))
    implementation(libs.kotlin.stdlib)
    implementation(libs.kotlinx.coroutines.core)
    implementation(libs.kotlinx.coroutines.android)
    implementation(libs.androidx.annotation)
    implementation(libs.dagger)
    implementation(project(":SystemUI-common"))
    implementation(project(":SystemUI-pods-dagger"))
    implementation(files("${rootProject.projectDir}/libs/prebuilts/tracinglib-platform.jar"))
    implementation(files("${rootProject.projectDir}/libs/systemui-flags.jar"))
}
