// GENERATED by scripts/scaffold_aosp_modules.py — AOSP bp 1:1
// AOSP bp module: SystemUI-proto (bp path: .)
// SystemUI protobuf.nano generated classes (Flags, etc.)

plugins {
    alias(libs.plugins.kotlin.jvm)
}

java {
    sourceCompatibility = JavaVersion.VERSION_21
    targetCompatibility = JavaVersion.VERSION_21
}

kotlin {
    jvmToolchain(21)
}

dependencies {
    // Framework APIs - provided by system at runtime
    compileOnly(files("${rootProject.projectDir}/libs/framework.jar"))
    implementation(libs.kotlin.stdlib)
}
