// GENERATED by scripts/scaffold_aosp_modules.py — AOSP bp 1:1
// AOSP bp module: api (bp path: pods/com/android/systemui/dagger)
// Dagger qualifiers (Application, Background, Main, etc.)

plugins {
    alias(libs.plugins.android.library)
    alias(libs.plugins.kotlin.android)
}

android {
    namespace = "com.android.systemui.dagger"
    compileSdkPreview = "SysUISdk"

    defaultConfig {
        minSdk = 32
    }

    sourceSets {
        getByName("main") {
            java.srcDirs("src/main/java")
            manifest.srcFile("src/main/AndroidManifest.xml")
        }
    }

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_21
        targetCompatibility = JavaVersion.VERSION_21
    }

    kotlin {
        jvmToolchain(21)
    }

    lint {
        abortOnError = false
    }

}

dependencies {
    compileOnly(files("${rootProject.projectDir}/libs/framework.jar"))
    compileOnly(libs.dagger)
    implementation(libs.androidx.annotation)
    implementation(libs.kotlin.stdlib)
}
